version: '3.5'

services:
  rabbit:
    container_name: symfony-api-platform-rabbitmq
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./docker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672 #Puerto de entrada/salida de nuestra cola de mensajer√≠a
      - 15672:15672 #Puertos de interfaz grafica
    networks:
      - symfony-api-platform-network

networks:
  symfony-api-platform-network:
    external: true